# Generated by Django 4.0.4 on 2022-05-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dis_cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cause', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dis_diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dis_symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('symptom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dis_treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Details', models.TextField()),
                ('Causes', models.TextField(null=True)),
                ('Symptoms', models.TextField()),
                ('Diagnosis', models.TextField(null=True)),
                ('Treatment', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
