# Generated by Django 4.0.4 on 2022-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('x_ray', models.TextField()),
                ('others', models.TextField(blank=b'I01\n', null=b'I01\n')),
            ],
        ),
    ]
