# Generated by Django 4.0.4 on 2022-06-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='ct',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='diseases',
            name='fev',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='diseases',
            name='ratio',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='diseases',
            name='rv',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='diseases',
            name='tlc',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='diseases',
            name='vc',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='diseases',
            name='others',
            field=models.TextField(blank=b'I01\n', max_length=100, null=b'I01\n'),
        ),
    ]
