# Generated by Django 4.0.4 on 2022-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_diseases_ct_diseases_fev_diseases_ratio_diseases_rv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='others',
            field=models.TextField(blank=b'I01\n', null=b'I01\n'),
        ),
    ]
