# Generated by Django 4.0.4 on 2022-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_diseases_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='ct',
            field=models.TextField(blank=b'I01\n', null=b'I01\n'),
        ),
    ]
