# Generated by Django 4.0.4 on 2022-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_diseases_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='physical',
            field=models.TextField(blank=b'I01\n', null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
