# Generated by Django 4.0.4 on 2022-06-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_diseases_physical'),
    ]

    operations = [
        migrations.CreateModel(
            name='pred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='pred/%y/%m/%d')),
            ],
        ),
    ]
