# Generated by Django 4.0.4 on 2022-06-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='pred',
            name='name',
            field=models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='pred',
            name='img',
            field=models.ImageField(upload_to='pred/%y/%m/%d'),
        ),
    ]
